name: jobs

volumes:
  postgres_data:
  rabbitmq_data:

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./config/database/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=application
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user -d postgres"]
      interval: 10s
      retries: 5
      timeout: 5s

  rabbitmq:
    build:
      context: ./config/rabbitmq
      dockerfile: Dockerfile
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia/
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 3