"""position company id

Revision ID: 1abad6d51fb2
Revises: ecedbd5cc8b1
Create Date: 2024-08-26 22:02:23.271268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1abad6d51fb2'
down_revision: Union[str, None] = 'ecedbd5cc8b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate', 'social_accounts')
    op.add_column('positions', sa.Column('company_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'positions', ['company_id'])
    op.create_foreign_key(None, 'positions', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'positions', type_='foreignkey')
    op.drop_constraint(None, 'positions', type_='unique')
    op.drop_column('positions', 'company_id')
    op.add_column('candidate', sa.Column('social_accounts', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
