"""confirm_code_table

Revision ID: 1c3ad3002250
Revises: 3d65f0f2df6e
Create Date: 2024-08-18 16:16:39.267519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c3ad3002250'
down_revision: Union[str, None] = '3d65f0f2df6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confirm_codes',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('code', sa.VARCHAR(length=6), nullable=False),
    sa.Column('status', sa.Enum('SENDED', 'USED', name='confirmstatuscode'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('confirm_codes')
    # ### end Alembic commands ###
