"""candidate_fk

Revision ID: 2ed2760e1008
Revises: 929c4d6511f7
Create Date: 2024-08-21 06:37:24.416091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ed2760e1008'
down_revision: Union[str, None] = '929c4d6511f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_experience', sa.Column('candidate_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'candidate_experience', ['candidate_id'])
    op.create_foreign_key(None, 'candidate_experience', 'candidate', ['candidate_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidate_experience', type_='foreignkey')
    op.drop_constraint(None, 'candidate_experience', type_='unique')
    op.drop_column('candidate_experience', 'candidate_id')
    # ### end Alembic commands ###
