"""remove_unique_name

Revision ID: 5c41a0eeb4f0
Revises: e8b5c6eb8a22
Create Date: 2024-08-17 21:18:29.625296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c41a0eeb4f0'
down_revision: Union[str, None] = 'e8b5c6eb8a22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('admin_staff_name_key', 'admin_staff', type_='unique')
    op.drop_constraint('candidate_experience_candidate_id_key', 'candidate_experience', type_='unique')
    op.drop_constraint('candidate_experience_candidate_id_fkey', 'candidate_experience', type_='foreignkey')
    op.drop_column('candidate_experience', 'candidate_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_experience', sa.Column('candidate_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('candidate_experience_candidate_id_fkey', 'candidate_experience', 'candidate', ['candidate_id'], ['id'])
    op.create_unique_constraint('candidate_experience_candidate_id_key', 'candidate_experience', ['candidate_id'])
    op.create_unique_constraint('admin_staff_name_key', 'admin_staff', ['name'])
    # ### end Alembic commands ###
