"""confirm code

Revision ID: 905f96c6e965
Revises: d8af8deeffe4
Create Date: 2024-08-31 11:20:19.357718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '905f96c6e965'
down_revision: Union[str, None] = 'd8af8deeffe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('confirm_codes', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint('confirm_codes_email_key', 'confirm_codes', type_='unique')
    op.drop_column('confirm_codes', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('confirm_codes', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_unique_constraint('confirm_codes_email_key', 'confirm_codes', ['email'])
    op.drop_column('confirm_codes', 'updated_at')
    # ### end Alembic commands ###
