"""backrefs

Revision ID: 929c4d6511f7
Revises: 1c3ad3002250
Create Date: 2024-08-20 08:51:22.948590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '929c4d6511f7'
down_revision: Union[str, None] = '1c3ad3002250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    companymanagerrole = sa.Enum('ADMIN', 'MANAGER', name='companymanagerrole')
    companymanagerrole.create(op.get_bind())

    op.add_column('company', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('company', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('company_manager', sa.Column('role', companymanagerrole, nullable=False))
    op.add_column('confirm_codes', sa.Column('auth_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'confirm_codes', 'auth', ['auth_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'confirm_codes', type_='foreignkey')
    op.drop_column('confirm_codes', 'auth_id')
    op.drop_column('company_manager', 'role')
    op.drop_column('company', 'updated_at')
    op.drop_column('company', 'created_at')
    # ### end Alembic commands ###
