"""remove_unique_password

Revision ID: b223064efbd7
Revises: 5c41a0eeb4f0
Create Date: 2024-08-17 21:21:19.478633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b223064efbd7'
down_revision: Union[str, None] = '5c41a0eeb4f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('admin_staff_password_key', 'admin_staff', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('admin_staff_password_key', 'admin_staff', ['password'])
    # ### end Alembic commands ###
