"""company_image

Revision ID: e8b5c6eb8a22
Revises: d65fd6ef980a
Create Date: 2024-08-16 10:13:43.890063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8b5c6eb8a22'
down_revision: Union[str, None] = 'd65fd6ef980a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('image_link', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'image_link')
    # ### end Alembic commands ###
